table dim_ModalidadIngreso
	lineageTag: 78ecfbfb-da7f-4702-a836-7e1ec029b747

	column Carrera2
		dataType: string
		lineageTag: 790d7858-6f07-4cc5-b829-a9488bb79405
		summarizeBy: none
		sourceColumn: Carrera2

		annotation SummarizationSetBy = Automatic

	column Grupo
		dataType: string
		lineageTag: c3a9b3d2-cb79-4ac7-9718-b7179ad7dbbb
		summarizeBy: none
		sourceColumn: Grupo

		annotation SummarizationSetBy = Automatic

	column 'ID ModalidadIngreso'
		dataType: int64
		formatString: 0
		lineageTag: 5984ddb1-3862-4533-9cdb-a86b818e0763
		summarizeBy: none
		sourceColumn: ID ModalidadIngreso

		annotation SummarizationSetBy = Automatic

	partition dim_ModalidadIngreso = m
		mode: import
		source =
				let
				    TablaCarrera2Grupo = #table(
				        {"Carrera2", "Grupo"},
				        {
				            {"EGRESADO DE INSTITUTO UG", "INSTITUTO"},
				            {"EGRESADO DE INSTITUTO WA", "INSTITUTO"},
				            {"EGRESADO DE INSTITUTO WAS", "INSTITUTO"},
				            {"EGRESADO DE INSTITUTO WAV", "INSTITUTO"},
				            {"EGRESADO UNIVERSIDAD UG", "UNIVERSIDAD"},
				            {"EGRESADO UNIVERSIDAD WA", "UNIVERSIDAD"},
				            {"EGRESADO UNIVERSIDAD WAV", "UNIVERSIDAD"},
				            {"EGRESADO UPN UG", "UNIVERSIDAD"},
				            {"EGRESADO UPN WA", "UNIVERSIDAD"},
				            {"EGRESADO UPN WAV", "UNIVERSIDAD"},
				            {"TRASLADO EXTERNO UG", "UNIVERSIDAD"},
				            {"TRASLADO EXTERNO WA", "UNIVERSIDAD"},
				            {"TRASLADO EXTERNO WAS", "UNIVERSIDAD"},
				            {"TRASLADO EXTERNO WAV", "UNIVERSIDAD"},
				            {"EGRESADO UPN WAS", "UNIVERSIDAD"},
				            {"EGRESADO UNIVERSIDAD WAS", "UNIVERSIDAD"},
				            {"TRANSFERENCIA TEMPRANA", "UNIVERSIDAD"},
				            {"TRANSFERENCIA TEMPRANA WA", "UNIVERSIDAD"},
				            {"TRANSFERENCIA TEMPRANA WAS", "UNIVERSIDAD"},
				            {"TRANSFERENCIA TEMPRANA WAV", "UNIVERSIDAD"},
				            {"BECA MUJERES STEM WAS", "UNIVERSIDAD"},
				            {"EGRESADO DE INSTITUTO", "INSTITUTO"},
				            {"EGRESADO UNIVERSIDAD", "UNIVERSIDAD"},
				            {"EGRESADO UPN", "UNIVERSIDAD"},
				            {"TRASLADO EXTERNO", "UNIVERSIDAD"}
				        }
				    ),
				    #"Índice agregado" = Table.AddIndexColumn(TablaCarrera2Grupo, "ID ModalidadIngreso", 1, 1, Int64.Type)
				in
				    #"Índice agregado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

