table BBDD
	lineageTag: 1ce39c5b-31fa-42b1-b75d-6d80fd2b3776

	column Column1
		dataType: double
		lineageTag: 24a3c14b-ae86-44ed-9442-a0e4c7a44835
		summarizeBy: sum
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sede
		dataType: string
		lineageTag: a666f4a1-15e2-4436-8a2d-2b507c410404
		summarizeBy: none
		sourceColumn: Sede

		annotation SummarizationSetBy = Automatic

	column ConsejeroAdmision
		dataType: string
		lineageTag: 5bff06e6-ea03-4eaa-8b9e-eb115173bb21
		summarizeBy: none
		sourceColumn: ConsejeroAdmision

		annotation SummarizationSetBy = Automatic

	column EstudianteEntregoDocumentosParaConvalidacion
		dataType: string
		lineageTag: aabe245a-f9a0-4dfb-8f7e-864c86803516
		summarizeBy: none
		sourceColumn: EstudianteEntregoDocumentosParaConvalidacion

		annotation SummarizationSetBy = Automatic

	column Fecha_Recep
		dataType: dateTime
		formatString: d/mm/yyyy hh:nn:ss
		lineageTag: 3173da23-d354-4110-a313-75a38d7565fb
		summarizeBy: none
		sourceColumn: Fecha_Recep

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Carrera
		dataType: string
		lineageTag: 124d6037-c25c-4516-b76a-d72d18565895
		summarizeBy: none
		sourceColumn: Carrera

		annotation SummarizationSetBy = Automatic

	column Programa
		dataType: string
		lineageTag: 2d0856cf-5325-4c74-bd24-031907feefef
		summarizeBy: none
		sourceColumn: Programa

		annotation SummarizationSetBy = Automatic

	column Campania
		dataType: string
		lineageTag: 9e279622-eb3e-4883-ae7d-0e7a74d5d45c
		summarizeBy: none
		sourceColumn: Campania

		annotation SummarizationSetBy = Automatic

	column Codigo
		dataType: string
		lineageTag: 0b90052d-7c21-4678-8a09-7f5aeb74cdb6
		summarizeBy: none
		sourceColumn: Codigo

		annotation SummarizationSetBy = Automatic

	column ApellidoPaterno
		dataType: string
		lineageTag: bac1101c-6edf-465d-aa0c-d76e9f1f9151
		summarizeBy: none
		sourceColumn: ApellidoPaterno

		annotation SummarizationSetBy = Automatic

	column ApellidoMaterno
		dataType: string
		lineageTag: f229749d-ea0c-48b6-80ea-cb2dac832abd
		summarizeBy: none
		sourceColumn: ApellidoMaterno

		annotation SummarizationSetBy = Automatic

	column Nombres
		dataType: string
		lineageTag: 2756a50d-f841-4e25-9c95-3bf3134de2c5
		summarizeBy: none
		sourceColumn: Nombres

		annotation SummarizationSetBy = Automatic

	column ModalidadIngreso
		dataType: string
		lineageTag: 700fb635-3b86-4fb9-af92-bfb3aa12cef3
		summarizeBy: none
		sourceColumn: ModalidadIngreso

		annotation SummarizationSetBy = Automatic

	column SubModalidadIngreso
		dataType: string
		lineageTag: c144d4e3-1d9c-446d-9e8d-e45ea8c8174f
		summarizeBy: none
		sourceColumn: SubModalidadIngreso

		annotation SummarizationSetBy = Automatic

	column EstadoConvalidacion
		dataType: string
		lineageTag: 9e53abd7-13f6-4fe3-8abf-5f191896f4af
		summarizeBy: none
		sourceColumn: EstadoConvalidacion

		annotation SummarizationSetBy = Automatic

	column FechaCompletoConvalidacion
		dataType: dateTime
		formatString: Short Date
		lineageTag: af8c9575-7fa0-4be8-899c-cefe02816c3c
		summarizeBy: none
		sourceColumn: FechaCompletoConvalidacion

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ResponsableConvalidacion
		dataType: string
		lineageTag: 78b172e2-4903-49e5-8b09-9795d349c30d
		summarizeBy: none
		sourceColumn: ResponsableConvalidacion

		annotation SummarizationSetBy = Automatic

	column UltimoEstadoRevisionDocumento
		dataType: string
		lineageTag: 67677e04-0c62-40b8-886d-5142e8c84185
		summarizeBy: none
		sourceColumn: UltimoEstadoRevisionDocumento

		annotation SummarizationSetBy = Automatic

	column InstitucionConvalidacion
		dataType: string
		lineageTag: 88f8c67e-4954-4dd9-bd6a-cefc3875afe1
		summarizeBy: none
		sourceColumn: InstitucionConvalidacion

		annotation SummarizationSetBy = Automatic

	column VersionCRM
		dataType: string
		lineageTag: cdd653ef-bef6-4f93-b310-a1538705676a
		summarizeBy: none
		sourceColumn: VersionCRM

		annotation SummarizationSetBy = Automatic

	column TieneConvalidacion
		dataType: string
		lineageTag: a77c0814-d775-48aa-aef2-0b112598c68a
		summarizeBy: none
		sourceColumn: TieneConvalidacion

		annotation SummarizationSetBy = Automatic

	column ConvalidacionPaquete
		dataType: string
		lineageTag: 16066deb-9d27-4fed-9fec-c871729f7129
		summarizeBy: none
		sourceColumn: ConvalidacionPaquete

		annotation SummarizationSetBy = Automatic

	column 'ID Carrera'
		dataType: int64
		formatString: 0
		lineageTag: 956380ac-5262-4ed3-8f39-11cebac5192d
		summarizeBy: none
		sourceColumn: ID Carrera

		annotation SummarizationSetBy = Automatic

	column 'ID Sede'
		dataType: int64
		formatString: 0
		lineageTag: 0b168bd0-681e-49cb-a964-05b442ed51c4
		summarizeBy: none
		sourceColumn: ID Sede

		annotation SummarizationSetBy = Automatic

	column 'ID Estado Convalidacion'
		dataType: int64
		formatString: 0
		lineageTag: 76cf7627-ef18-44f2-82fb-23fb38a315a3
		summarizeBy: none
		sourceColumn: ID Estado Convalidacion

		annotation SummarizationSetBy = Automatic

	column 'ID ModalidadIngreso'
		dataType: int64
		formatString: 0
		lineageTag: 71fd6231-b273-491e-b601-facc8336d2ba
		summarizeBy: none
		sourceColumn: ID ModalidadIngreso

		annotation SummarizationSetBy = Automatic

	column NombresCompletos
		dataType: string
		lineageTag: 0014dbdf-943b-4035-a404-c41957f15bcf
		summarizeBy: none
		sourceColumn: NombresCompletos

		annotation SummarizationSetBy = Automatic

	column Fech_Rec_hora = ```
			
			VAR HoraVal = VALUE ( BBDD[Fecha_Recep] )
			VAR EsTiempoSerial = NOT ISBLANK(HoraVal) && HoraVal < 1          -- formato hora (0–1)
			VAR EsDespuesDe6 =
			    IF (
			        EsTiempoSerial,
			        HoraVal > TIME ( 18, 0, 0 ),   -- si viene como hora (0–1)
			        HoraVal > 18                    -- si viene como número de hora (ej. 19 o 18.5)
			    )
			RETURN
			IF (
			    ISBLANK ( BBDD[Fecha_Recep] ),
			    BLANK (),
			    BBDD[Fecha_Recep] + IF ( EsDespuesDe6, 1, 0 )
			)
			
			```
		formatString: General Date
		lineageTag: 7b721780-3ed0-4aaa-9122-4c84d78075a5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DIASEM = ```
			
			IF (
			    ISBLANK ( BBDD[Fech_Rec_hora] ),
			    BLANK (),
			    WEEKDAY ( BBDD[Fech_Rec_hora], 2 )
			)
			
			```
		formatString: 0
		lineageTag: dbbc16db-c921-4d1b-886d-091abf3689b6
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Plazo = ```
			
			IF (
			    ISBLANK ( BBDD[Fech_Rec_hora] ),
			    BLANK (),
			    VAR dia = BBDD[DIASEM]            -- asume que ya tienes la columna DIASEM (1=Lun ... 7=Dom)
			    VAR diasASumar =
			        SWITCH (
			            TRUE (),
			            dia = 1, 3,
			            dia = 2, 3,
			            dia = 3, 5,
			            dia = 4, 5,
			            dia = 5, 5,
			            dia = 6, 4,
			            dia = 7, 3,
			            0                             -- valor por defecto si no coincide
			        )
			    RETURN
			        BBDD[Fech_Rec_hora] + diasASumar
			)
			
			```
		formatString: General Date
		lineageTag: 21a8fc86-15ae-4e25-8ec0-7427b19825c0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Columna2 = ```
			
			BBDD[EstadoConvalidacion] & BBDD[EstudianteEntregoDocumentosParaConvalidacion]
			
			```
		lineageTag: 42ee025a-dd2c-457c-9b3a-926fddf72f97
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Est_prev =
			
			VAR modalidad = BBDD[ModalidadIngreso]
			VAR entrega = BBDD[EstudianteEntregoDocumentosParaConvalidacion]
			VAR convPaq = BBDD[ConvalidacionPaquete]
			VAR estadoConv = BBDD[EstadoConvalidacion]
			
			-- Condiciones base
			VAR esEgresadoUPN = NOT( ISBLANK(modalidad) ) && LEFT(modalidad, 12) = "EGRESADO UPN"
			VAR entregaEsSI = entrega = "SI"
			VAR convPaqValido = NOT(ISBLANK(convPaq)) && convPaq <> "No aplica"
			VAR estadoPendiente = estadoConv = "Pendiente"
			
			VAR resultado =
			    IF(
			        ISBLANK(modalidad),
			        BLANK(),
			        IF(
			            esEgresadoUPN && entregaEsSI,
			            "Egresado",
			            IF(
			                entregaEsSI && convPaqValido && estadoPendiente,
			                "Paquete",
			                BLANK()
			            )
			        )
			    )
			
			RETURN
			IF( ISBLANK(resultado), "Regular", resultado )
		lineageTag: 277bc72f-6f45-43b2-b34e-786ba531f8bb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Estado = ```
			
			SWITCH(
			    TRUE(),
			    BBDD[EstadoConvalidacion] = "Pendiente" && BBDD[EstudianteEntregoDocumentosParaConvalidacion] = "SI", "Pendiente",
			    BBDD[EstadoConvalidacion] = "Pendiente" && BBDD[EstudianteEntregoDocumentosParaConvalidacion] = "NO", "No Iniciado - Admisión",
			    BBDD[EstadoConvalidacion] = "Enviado" && BBDD[EstudianteEntregoDocumentosParaConvalidacion] = "SI", "Cerrado",
			    BLANK()
			)
			
			```
		lineageTag: a3d3fa1e-5079-4a50-aaee-4e23511520d7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Dif_pend = ```
			
			IF(
			    BBDD[Columna2] = "PendienteSI",
			    DATEDIFF(
			        DATE( YEAR( BBDD[Plazo] ), MONTH( BBDD[Plazo] ), DAY( BBDD[Plazo] ) ),
			        TODAY(),
			        DAY
			    ),
			    BLANK()
			)
			
			```
		formatString: 0
		lineageTag: 9e7faa90-2a6e-431d-be7d-5deffec57ca9
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Columna3 =
			
			IF(
			    ISBLANK( BBDD[Dif_pend] ),
			    BLANK(),
			    IF( BBDD[Dif_pend] > 0, "Fuera", "Dentro" )
			)
		lineageTag: 73af460b-1765-40bf-8b13-8c461ec921b4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Dif_cerr = ```
			
			IF(
			    ISBLANK( BBDD[FechaCompletoConvalidacion] ) || ISBLANK( BBDD[Plazo] ),
			    BLANK(),
			    BBDD[FechaCompletoConvalidacion] - BBDD[Plazo]
			)
			
			```
		formatString: General Date
		lineageTag: cd4b12f9-d4cc-4e73-b1ea-30c7e688f2a5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column SLA_cerr = ```
			
			IF(
			    ISBLANK( BBDD[Dif_cerr] ),
			    BLANK(),
			    IF( BBDD[Dif_cerr] > 0, "Fuera", "Dentro" )
			)
			
			```
		lineageTag: 6be61770-3d61-48f1-9505-b801c85af359
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Situac = ```
			
			BBDD[SLA_cerr] & BBDD[Columna3]
			
			```
		lineageTag: 5de98525-e0ae-4622-85ee-14c3d8064425
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column FechaDia
		dataType: dateTime
		formatString: Short Date
		lineageTag: 06918697-300b-48ed-af45-2d5fa69a77a3
		summarizeBy: none
		sourceColumn: FechaDia

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SLA_OFI =
			
			VAR limite = BBDD[Fecha_Limite_SLA]
			VAR cierre = BBDD[FechaCompletoConvalidacion]
			VAR referencia = IF( NOT ISBLANK(cierre), cierre, NOW() )
			RETURN IF( ISBLANK(limite), BLANK(), IF( referencia <= limite, "DENTRO", "FUERA" ) )
		lineageTag: feb10261-3342-4f8b-8d28-0fcb24c7b80a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Fecha CompletoConvalidacion'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 05e2e99a-28e5-4597-8f11-13e1368e7fba
		summarizeBy: none
		sourceColumn: Fecha CompletoConvalidacion

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fecha Año - Sem' =
			
			VAR fechaBase =
			    IF(
			        ISBLANK(BBDD[FechaCompletoConvalidacion]),
			        BBDD[Fecha_Recep],
			        BBDD[FechaCompletoConvalidacion]
			    )
			RETURN
			IF(
			    ISBLANK(fechaBase),
			    BLANK(),
			    FORMAT(fechaBase, "YYYY") & "-S" & FORMAT(fechaBase, "WW")
			)
		lineageTag: cd064c5d-9797-498d-b63b-a5d53140ce53
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Volumen = ```
			
			VAR _fcc_text =
			    TRIM( SUBSTITUTE( BBDD[FechaCompletoConvalidacion] & "", UNICHAR(160), " " ) )
			VAR _fr_text  =
			    TRIM( SUBSTITUTE( BBDD[Fecha_Recep] & "", UNICHAR(160), " " ) )
			
			-- Intenta convertir a fecha (si tu dato es "fecha y hora", usa DATETIMEVALUE en vez de DATEVALUE)
			VAR _fcc_date =
			    IF( _fcc_text <> "", DATEVALUE( _fcc_text ), BLANK() )
			
			VAR _fr_date  =
			    IF( _fr_text <> "", DATEVALUE( _fr_text ), BLANK() )
			
			RETURN
			COALESCE( _fcc_date, _fr_date )
			
			```
		formatString: Long Date
		lineageTag: e1f3aab2-ebcf-4c42-a628-472e6cdb8215
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Campaña.ID Campaña'
		dataType: int64
		formatString: 0
		lineageTag: d3ca5dca-3973-45ae-86e0-46a216d660d0
		summarizeBy: none
		sourceColumn: Campaña.ID Campaña

		annotation SummarizationSetBy = Automatic

	column Fecha_Limite_SLA = ```
			
			VAR SLA_DiasHabiles = 3
			VAR HoraCorte       = TIME(19,0,0)  -- única hora de control
			VAR Feriados =
			{
			    DATE(2025,1,1),   -- Año Nuevo
			    DATE(2025,4,17),  -- Jueves Santo
			    DATE(2025,4,18),  -- Viernes Santo
			    DATE(2025,5,1),   -- Día del Trabajo
			    DATE(2025,6,29),  -- San Pedro y San Pablo
			    DATE(2025,7,28),  -- Fiestas Patrias
			    DATE(2025,7,29),  -- Fiestas Patrias
			    DATE(2025,8,30),  -- Santa Rosa de Lima
			    DATE(2025,10,8),  -- Combate de Angamos
			    DATE(2025,11,1),  -- Todos los Santos
			    DATE(2025,12,8),  -- Inmaculada Concepción
			    DATE(2025,12,9),  -- Batalla de Ayacucho
			    DATE(2025,12,25),  -- Navidad
			    --2026
			    DATE(2026,1,1),   -- Año Nuevo
			    DATE(2026,4,2),   -- Jueves Santo
			    DATE(2026,4,3),   -- Viernes Santo
			    DATE(2026,5,1),   -- Día del Trabajo
			    DATE(2026,6,7),   -- Batalla de Arica y Día de la Bandera
			    DATE(2026,6,29),  -- San Pedro y San Pablo
			    DATE(2026,7,23),  -- Día de la Fuerza Aérea del Perú
			    DATE(2026,7,28),  -- Fiestas Patrias
			    DATE(2026,7,29),  -- Fiestas Patrias
			    DATE(2026,8,6),   -- Batalla de Junín
			    DATE(2026,8,30),  -- Santa Rosa de Lima
			    DATE(2026,10,8),  -- Combate de Angamos
			    DATE(2026,11,1),  -- Todos los Santos
			    DATE(2026,12,8),  -- Inmaculada Concepción
			    DATE(2026,12,9),  -- Batalla de Ayacucho
			    DATE(2026,12,25)  -- Navidad
			
			}
			VAR _dtRecep    = BBDD[Fecha_Recep]
			VAR _tieneRecep = NOT ISBLANK(_dtRecep)
			RETURN
			IF (
			    NOT _tieneRecep,
			    BLANK(),
			    VAR _fechaBase = DATEVALUE(_dtRecep)
			    VAR _horaRaw   = TIMEVALUE(_dtRecep)
			
			    /* Primer día hábil >= fechaBase */
			    VAR _inicioHabil =
			        MINX (
			            FILTER (
			                ADDCOLUMNS (
			                    CALENDAR ( _fechaBase, _fechaBase + 60 ),
			                    "EsFinde",   WEEKDAY ( [Date], 2 ) >= 6,
			                    "EsFeriado", [Date] IN Feriados
			                ),
			                [Date] >= _fechaBase && [EsFinde] = FALSE && [EsFeriado] = FALSE
			            ),
			            [Date]
			        )
			
			    /*
			        Si la hora de recepción es >= HoraCorte,
			        arrancamos al siguiente día hábil (misma hora de recepción).
			        (No se usa HoraInicioLaboral ni HoraReinicio)
			    */
			    VAR _inicioFinalDT =
			        IF (
			            _horaRaw >= HoraCorte,
			            MINX (
			                FILTER (
			                    ADDCOLUMNS (
			                        CALENDAR ( _inicioHabil + 1, _inicioHabil + 60 ),
			                        "EsFinde",   WEEKDAY ( [Date], 2 ) >= 6,
			                        "EsFeriado", [Date] IN Feriados
			                    ),
			                    [EsFinde] = FALSE && [EsFeriado] = FALSE
			                ),
			                [Date]
			            ) + _horaRaw,
			            _inicioHabil + _horaRaw
			        )
			
			    /* Sumar 3 días hábiles desde el inicio válido */
			    VAR _startDate = DATEVALUE ( _inicioFinalDT )
			    VAR _startTime = TIMEVALUE ( _inicioFinalDT )
			
			    VAR _habilesBase =
			        FILTER (
			            ADDCOLUMNS (
			                CALENDAR ( _startDate, _startDate + 60 ),
			                "EsFinde",   WEEKDAY ( [Date], 2 ) >= 6,
			                "EsFeriado", [Date] IN Feriados
			            ),
			            [EsFinde] = FALSE && [EsFeriado] = FALSE
			        )
			
			    VAR _indexados =
			        ADDCOLUMNS (
			            _habilesBase,
			            "idx",
			                VAR d = [Date]
			                RETURN COUNTROWS ( FILTER ( _habilesBase, [Date] <= d ) ) - 1
			        )
			
			    VAR _fechaLimite =
			        MINX ( FILTER ( _indexados, [idx] = SLA_DiasHabiles ), [Date] )
			
			    RETURN _fechaLimite + _startTime
			)
			
			```
		formatString: General Date
		lineageTag: 56179099-b514-4084-bf53-843c38c01398
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'SLA NEW' =
			
			VAR limite = BBDD[Fecha_Limite_SLA]
			VAR cierre = BBDD[FechaCompletoConvalidacion]
			VAR referencia = IF( NOT ISBLANK(cierre), cierre, NOW() )
			RETURN IF( ISBLANK(limite), BLANK(), IF( referencia <= limite, "DENTRO", "FUERA" ) )
		lineageTag: c12d9c43-8b38-45e6-9e1b-3fc564bb9ec0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Sem = ```
			
			VAR _Anio   = YEAR(BBDD[Fecha_Recep])
			VAR _Semana = WEEKNUM(BBDD[Fecha_Recep], 2)   -- Semana inicia lunes
			RETURN
			FORMAT(_Anio, "0000") & "-S" & FORMAT(_Semana, "00")
			
			
			```
		lineageTag: 5da4a510-a8f7-4b5b-9125-7523a011b2d3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Campaña formato' = ```
			
			SWITCH(
			    TRUE(),
			    BBDD[Campania] = "2022-01 PG", "2022-01",
			    BBDD[Campania] = "2022-01 WA", "2022-01",
			    BBDD[Campania] = "2022-02 PG", "2022-02",
			    BBDD[Campania] = "2022-02 WA", "2022-02",
			    BBDD[Campania] = "CAMPAÑA 2022-1 CAJAMARCA", "2022-01",
			    BBDD[Campania] = "CAMPAÑA 2022-1 COMAS", "2022-01",
			    BBDD[Campania] = "CAMPAÑA 2022-1 LIMA CENTRO", "2022-01",
			    BBDD[Campania] = "CAMPAÑA 2022-1 LIMA ESTE", "2022-01",
			    BBDD[Campania] = "CAMPAÑA 2022-1 LIMA NORTE", "2022-01",
			    BBDD[Campania] = "CAMPAÑA 2022-1 LIMA SUR", "2022-01",
			    BBDD[Campania] = "CAMPAÑA 2022-1 TRUJILLO", "2022-01",
			    BBDD[Campania] = "CAMPAÑA 2022-1 WAC", "2022-01",
			    BBDD[Campania] = "CAMPAÑA 2022-1 WACO", "2022-01",
			    BBDD[Campania] = "CAMPAÑA 2022-1 WALC", "2022-01",
			    BBDD[Campania] = "CAMPAÑA 2022-1 WALE", "2022-01",
			    BBDD[Campania] = "CAMPAÑA 2022-1 WALN", "2022-01",
			    BBDD[Campania] = "CAMPAÑA 2022-1 WALS", "2022-01",
			    BBDD[Campania] = "CAMPAÑA 2022-1 WAT", "2022-01",
			    BBDD[Campania] = "CAMPAÑA 2022-1 WALE", "2022-01",
			    BBDD[Campania] = "2024-02 PG", "2024-02",
			    BBDD[Campania] = "2024-02 WA", "2024-02",
			    BBDD[Campania] = "2024-02 WV", "2024-02",
			    BBDD[Campania] = "2025-01 PG", "2025-01",
			    BBDD[Campania] = "2025-01 WA", "2025-01",
			    BBDD[Campania] = "2025-01 WS", "2025-01",
			    BBDD[Campania] = "2025-01 WV", "2025-01",
			    BBDD[Campania] = "2025-02 PG", "2025-02",
			    BBDD[Campania] = "2025-02 WA", "2025-02",
			    BBDD[Campania] = "2026-01 PG", "2026-01",
			    BBDD[Campania] = "2026-01 WA", "2026-01",
			    BLANK()
			)
			
			```
		lineageTag: d63c496d-9c28-40c5-be3e-7b11847d8a8a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Sem_camp = ```
			
			SWITCH(
			    TRUE(),
			    BBDD[Sem] = "S01", 19,
			    BBDD[Sem] = "S02", 20,
			    BBDD[Sem] = "S03", 21,
			    BBDD[Sem] = "S04", 22,
			    BBDD[Sem] = "S05", 23,
			    BBDD[Sem] = "S06", 24,
			    BBDD[Sem] = "S07", 25,
			    BBDD[Sem] = "S08", 26,
			    BBDD[Sem] = "S09", 27,
			    BBDD[Sem] = "S10", 28,
			    BBDD[Sem] = "S11", 29,
			    BBDD[Sem] = "S12", 30,
			    BBDD[Sem] = "S13", 31,
			    BBDD[Sem] = "S14", 32,
			    BBDD[Sem] = "S15", 33,
			    BBDD[Sem] = "S36", 1,
			    BBDD[Sem] = "S37", 2,
			    BBDD[Sem] = "S38", 3,
			    BBDD[Sem] = "S39", 4,
			    BBDD[Sem] = "S40", 5,
			    BBDD[Sem] = "S41", 6,
			    BBDD[Sem] = "S42", 7,
			    BBDD[Sem] = "S43", 8,
			    BBDD[Sem] = "S44", 9,
			    BBDD[Sem] = "S45", 10,
			    BBDD[Sem] = "S46", 11,
			    BBDD[Sem] = "S47", 12,
			    BBDD[Sem] = "S48", 13,
			    BBDD[Sem] = "S49", 14,
			    BBDD[Sem] = "S50", 15,
			    BBDD[Sem] = "S51", 16,
			    BBDD[Sem] = "S52", 17,
			    BBDD[Sem] = "S53", 18,
			    BLANK()
			)
			
			```
		formatString: 0
		lineageTag: 8575891b-5b95-4593-ad26-7a5b9a1b54e2
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Tipo paquete' = ```
			
			SWITCH(
			    TRUE(),
			    BBDD[ConvalidacionPaquete] = "P 1 - 2 - 3", "Paquete",
			    BBDD[ConvalidacionPaquete] = "P 1 - 2 - 3 - 4", "Paquete",
			    BBDD[ConvalidacionPaquete] = "P 1 - 2", "Paquete",
			    BBDD[ConvalidacionPaquete] = "P 1", "Paquete",
			    BBDD[ConvalidacionPaquete] = "No aplica", "Regular",
			    BBDD[ConvalidacionPaquete] = " ", "Regular",
			    ISBLANK(BBDD[ConvalidacionPaquete]), "Regular",
			    "Regular"
			)
			
			```
		lineageTag: cea49367-9854-4481-a12a-914920d8cb87
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Campus
		dataType: string
		lineageTag: 02b8fb59-cc16-43c1-95b0-0372c0344a7d
		summarizeBy: none
		sourceColumn: Campus

		annotation SummarizationSetBy = Automatic

	column 'ID CAMPUS'
		dataType: int64
		formatString: 0
		lineageTag: 7dcb5cc0-b8ea-47e5-b813-e2084fb4bc62
		summarizeBy: sum
		sourceColumn: ID CAMPUS

		annotation SummarizationSetBy = Automatic

	column Fecha_ModificaciónNomDia = ```
			
			VAR _fecha = DATEVALUE( BBDD[FechaDia] )
			RETURN
			IF(
			    ISBLANK(_fecha),
			    BLANK(),
			    FORMAT(_fecha, "dd/MM/yy")
			)
			
			```
		dataType: string
		lineageTag: c595d93a-64e4-41c4-9832-3d5896c4d6e5
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Fecha_Orden = ```
			
			DATEVALUE( BBDD[FechaDia] )
			
			```
		formatString: Short Date
		lineageTag: 18db1f56-bc8f-4b48-9e79-54b51c849cdc
		summarizeBy: none

		changedProperty = DataType

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SemCompletado = ```
			
			VAR _Anio   = YEAR(BBDD[FechaCompletoConvalidacion])
			VAR _Semana = WEEKNUM(BBDD[FechaCompletoConvalidacion], 2)  -- Semana inicia lunes
			RETURN
			FORMAT(_Anio, "0000") & "-S" & FORMAT(_Semana, "00")
			
			```
		lineageTag: d679cb39-4dba-4076-b5d7-582346a67e6d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column SemIngreso =
			
			VAR _Semana = WEEKNUM(BBDD[Fecha_Recep], 2)  // 2 = la semana empieza en lunes
			RETURN
			"S" & FORMAT(_Semana, "00")
		lineageTag: 66fe71fc-363c-4840-84c6-6891eac343a3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Pronto_a_Vencer =
			
			VAR limite = BBDD[Fecha_Limite_SLA]
			VAR cierre = BBDD[FechaCompletoConvalidacion]
			VAR referencia = IF( NOT ISBLANK(cierre), cierre, NOW() )
			VAR diasAviso = 1   -- Puedes ajustar este número
			VAR diferencia = limite - referencia
			RETURN
			IF(
			    ISBLANK(limite),
			    BLANK(),
			    IF(
			        referencia <= limite          -- Aún está dentro del SLA
			        && diferencia <= diasAviso    -- Falta X días para vencer
			        && diferencia >= 0,           -- Aún no venció
			        "PRONTO A VENCER",
			        BLANK()
			    )
			)
		lineageTag: e4c05a43-b8fb-4722-ad66-63fd79134062
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition BBDD = m
		mode: import
		source = ```
				let
				    Origen = SharePoint.Files("https://educorpperu.sharepoint.com/sites/OPERACIONESACADMICAS_izhusr/", [ApiVersion = 15]),
				    #"Conva xlsx_https://educorpperu sharepoint com/sites/OPERACIONESACADMICAS_izhusr/Documentos compartidos/Reportes/Reporte de Convalidaciones/" = Origen{[Name="Conva.xlsx",#"Folder Path"="https://educorpperu.sharepoint.com/sites/OPERACIONESACADMICAS_izhusr/Documentos compartidos/Reportes/Reporte de Convalidaciones/"]}[Content],
				    #"Libro de Excel importado" = Excel.Workbook(#"Conva xlsx_https://educorpperu sharepoint com/sites/OPERACIONESACADMICAS_izhusr/Documentos compartidos/Reportes/Reporte de Convalidaciones/"),
				    Sheet1_Sheet = #"Libro de Excel importado"{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Poner En Mayúsculas Cada Palabra" = Table.TransformColumns(#"Encabezados promovidos",{{"Sede", Text.Proper, type text}}),
				    #"Consultas combinadas1" = Table.NestedJoin(#"Poner En Mayúsculas Cada Palabra", {"Sede"}, dim_Sede, {"Sede"}, "dim_Sede", JoinKind.LeftOuter),
				    #"Se expandió dim_Sede" = Table.ExpandTableColumn(#"Consultas combinadas1", "dim_Sede", {"ID Sede"}, {"ID Sede"}),
				    #"Consultas combinadas2" = Table.NestedJoin(#"Se expandió dim_Sede", {"EstadoConvalidacion"}, dim_EstadoConvalidacion, {"Estado"}, "dim_EstadoConvalidacion", JoinKind.LeftOuter),
				    #"Se expandió dim_EstadoConvalidacion" = Table.ExpandTableColumn(#"Consultas combinadas2", "dim_EstadoConvalidacion", {"ID Estado Convalidacion"}, {"ID Estado Convalidacion"}),
				    #"Consultas combinadas3" = Table.NestedJoin(#"Se expandió dim_EstadoConvalidacion", {"ModalidadIngreso"}, dim_ModalidadIngreso, {"Carrera2"}, "dim_ModalidadIngreso", JoinKind.LeftOuter),
				    #"Se expandió dim_ModalidadIngreso" = Table.ExpandTableColumn(#"Consultas combinadas3", "dim_ModalidadIngreso", {"ID ModalidadIngreso"}, {"ID ModalidadIngreso"}),
				    #"Columna combinada insertada" = Table.AddColumn(#"Se expandió dim_ModalidadIngreso", "NombresCompletos", each Text.Combine({[Nombres], " ", [ApellidoPaterno], " ", [ApellidoMaterno]}), type text),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columna combinada insertada",{{"FechaNotificacionAcademia", type datetime}, {"FechaCompletoConvalidacion", type datetime}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"FechaNotificacionAcademia", "Fecha_Recep"}}),
				    #"Consultas combinadas" = Table.NestedJoin(#"Columnas con nombre cambiado", {"Carrera"}, dim_Carrera, {"Carrera"}, "dim_Carrera", JoinKind.LeftOuter),
				    #"Se expandió dim_Carrera" = Table.ExpandTableColumn(#"Consultas combinadas", "dim_Carrera", {"ID Carrera"}, {"ID Carrera"}),
				    #"Tipo cambiado con configuración regional" = Table.TransformColumnTypes(#"Se expandió dim_Carrera", {{"Fecha_Recep", type datetime}}, "es-PE"),
				    #"Tipo cambiado con configuración regional1" = Table.TransformColumnTypes(#"Tipo cambiado con configuración regional", {{"FechaCompletoConvalidacion", type datetime}}, "es-PE"),
				    #"Fecha insertada" = Table.AddColumn(#"Tipo cambiado con configuración regional1", "FechaDia", each Date.From([Fecha_Recep]), type date),
				    #"Fecha insertada1" = Table.AddColumn(#"Fecha insertada", "Fecha CompletoConvalidacion", each Date.From([FechaCompletoConvalidacion]), type date),
				    #"Tipo cambiado con configuración regional2" = Table.TransformColumnTypes(#"Fecha insertada1", {{"Fecha CompletoConvalidacion", type date}}, "es-PE"),
				    #"Consultas combinadas4" = Table.NestedJoin(#"Tipo cambiado con configuración regional2", {"Campania"}, Campaña, {"Campaña"}, "Campaña", JoinKind.LeftOuter),
				    #"Se expandió Campaña" = Table.ExpandTableColumn(#"Consultas combinadas4", "Campaña", {"ID Campaña"}, {"Campaña.ID Campaña"}),
				    #"Tipo cambiado con configuración regional3" = Table.TransformColumnTypes(#"Se expandió Campaña", {{"Fecha_Recep", type datetimezone}}, "es-PE"),
				    #"Filas ordenadas" = Table.Sort(#"Tipo cambiado con configuración regional3",{{"Fecha_Recep", Order.Descending}}),
				    #"Filas filtradas" = Table.SelectRows(#"Filas ordenadas", each ([Campania] = "2026-01 PG" or [Campania] = "2026-01 WA")),
				    #"Duplicados quitados" = Table.Distinct(#"Filas filtradas", {"Codigo"}),
				    #"Personalizada agregada" = Table.AddColumn(#"Duplicados quitados", "Campus", each 
				    if [Sede] = "Lima Sur" then "Chorrillos" 
				    else if [Sede] = "Lima Comas" then "Comas" 
				    else if [Sede] = "Lima Centro" then "Breña" 
				    else if [Sede] = "Lima Este" then "San Juan" 
				    else if [Sede] = "Lima Norte" then "Los Olivos" 
				    else if [Sede] = "Trujillo" then "Trujillo" 
				    else if [Sede] = "Cajamarca" then "Cajamarca" 
				    else if [Sede] = "Trujillo San Isidro" then "Trujillo" 
				    else if [Sede] = "Virtual" then "Virtual" 
				    else if [Sede] = "Lima Ate" then "Ate" 
				    else if [Sede] = "Chorrillos" then "Chorrillos" 
				    else if [Sede] = "Comas Satelite" then "Comas" 
				    else null),
				    #"Consultas combinadas5" = Table.NestedJoin(#"Personalizada agregada", {"Campus"}, Dim_Campus, {"Campus"}, "Dim_Campus", JoinKind.LeftOuter),
				    #"Se expandió Dim_Campus" = Table.ExpandTableColumn(#"Consultas combinadas5", "Dim_Campus", {"ID CAMPUS"}, {"ID CAMPUS"})
				in
				    #"Se expandió Dim_Campus"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

