table ConvaErroresPaquete
	lineageTag: 09f0c123-89f2-428f-9a5e-274e539ad39e

	column Campania
		dataType: string
		lineageTag: a58f6240-ce49-48ad-88bf-aad922be2643
		summarizeBy: none
		sourceColumn: Campania

		annotation SummarizationSetBy = Automatic

	column Codigo
		dataType: string
		lineageTag: d51f29f1-3b07-49b7-af86-00dc0f39dce1
		summarizeBy: none
		sourceColumn: Codigo

		annotation SummarizationSetBy = Automatic

	column FechaCompletoConvalidacion
		dataType: dateTime
		formatString: General Date
		lineageTag: b3071084-197b-40f1-bb90-cd595075fa73
		summarizeBy: none
		sourceColumn: FechaCompletoConvalidacion

		annotation SummarizationSetBy = Automatic

	column ConvalidacionPaquete
		dataType: string
		lineageTag: 43f60a79-5a65-49f2-8fed-5dd05ea7e655
		summarizeBy: none
		sourceColumn: ConvalidacionPaquete

		annotation SummarizationSetBy = Automatic

	column 'ID ConvaErrores'
		dataType: int64
		formatString: 0
		lineageTag: 7d8299e3-f134-444e-a676-787582535eed
		summarizeBy: none
		sourceColumn: ID ConvaErrores

		annotation SummarizationSetBy = Automatic

	column ResponsableConvalidacion
		dataType: string
		lineageTag: 2560e027-75ca-4422-b155-56cec3d450e7
		summarizeBy: none
		sourceColumn: ResponsableConvalidacion

		annotation SummarizationSetBy = Automatic

	partition ConvaErroresPaquete = m
		mode: import
		source =
				let
				    Origen = Conex,
				    #"Conva xlsx_https://educorpperu sharepoint com/sites/OPERACIONESACADMICAS_izhusr/Documentos compartidos/Reportes/Reporte de Convalidaciones/" = Origen{[Name="Conva.xlsx",#"Folder Path"="https://educorpperu.sharepoint.com/sites/OPERACIONESACADMICAS_izhusr/Documentos compartidos/Reportes/Reporte de Convalidaciones/"]}[Content],
				    #"Libro de Excel importado" = Excel.Workbook(#"Conva xlsx_https://educorpperu sharepoint com/sites/OPERACIONESACADMICAS_izhusr/Documentos compartidos/Reportes/Reporte de Convalidaciones/"),
				    Sheet1_Sheet = #"Libro de Excel importado"{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Column1", Int64.Type}, {"Sede", type text}, {"ConsejeroAdmision", type text}, {"EstudianteEntregoDocumentosParaConvalidacion", type text}, {"FechaNotificacionAcademia", type datetime}, {"Carrera", type text}, {"Programa", type text}, {"Campania", type text}, {"Codigo", type text}, {"ApellidoPaterno", type text}, {"ApellidoMaterno", type text}, {"Nombres", type text}, {"ModalidadIngreso", type text}, {"SubModalidadIngreso", type text}, {"EstadoConvalidacion", type text}, {"FechaCompletoConvalidacion", type datetime}, {"ResponsableConvalidacion", type text}, {"UltimoEstadoRevisionDocumento", type text}, {"InstitucionConvalidacion", type text}, {"VersionCRM", type text}, {"TieneConvalidacion", type text}, {"ConvalidacionPaquete", type text}}),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Tipo cambiado",{"Campania", "Codigo", "FechaCompletoConvalidacion", "ResponsableConvalidacion", "ConvalidacionPaquete"}),
				    #"Filas filtradas" = Table.SelectRows(#"Otras columnas quitadas", each ([Campania] = "2026-01 PG" or [Campania] = "2026-01 WA") and ([ConvalidacionPaquete] <> null and [ConvalidacionPaquete] <> "No aplica                     ")),
				    #"Duplicados quitados" = Table.Distinct(#"Filas filtradas", {"Codigo"}),
				    #"Índice agregado" = Table.AddIndexColumn(#"Duplicados quitados", "ID ConvaErrores", 1, 1, Int64.Type)
				in
				    #"Índice agregado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

